package ai.meteor.kcode.platform

/** Preserve host ABI identity without exposing the entire implementation namespace. */
val PluginHostApiPackages: Set<String> = setOf(
    "ai.meteor.kcode.plugin.api",
    // Neutral composition/installation contracts retain identity; product entry classes stay private.
    "ai.meteor.kcode.plugin.AgentPluginManager",
    "ai.meteor.kcode.plugin.DynamicPluginSpec",
    "ai.meteor.kcode.plugin.KcodePluginMount",
    "ai.meteor.kcode.plugin.KcodePluginProfile",
    "ai.meteor.kcode.plugin.KcodePluginCompositionKt",
    "ai.meteor.kcode.plugin.ToolsPluginsKt",
    "ai.meteor.kcode.plugin.ui.api",
    // UIKit, neutral locale contracts, and vector resources are SDK primitives; dictionaries are private providers.
    "ai.meteor.kcode.localization",
    "org.jetbrains.compose.resources",
    "ai.meteor.kcode.ui.resources",
    "ai.meteor.kcode.ui.component",
    "ai.meteor.kcode.ui.design",
    "ai.meteor.kcode.ui.state.ConversationState",
    "kotlinx.io",
    "kotlinx.serialization",
    "kotlinx.schema",
    "ai.meteor.kcode.tools.search",
    "ai.meteor.kcode.AgentWorkspace",
    "ai.meteor.kcode.AgentWorkspaceEntry",
    "ai.meteor.kcode.AgentShellExecutor",
    "ai.meteor.kcode.AgentShellExecutor\$ExecutionResult",
    "ai.meteor.kcode.model",
    "ai.meteor.kcode.settings",
    "ai.meteor.kcode.tools.permission",
    "ai.meteor.kcode.chat",
    "ai.meteor.kcode.history",
    "ai.meteor.kcode.artifact",
    "ai.meteor.kcode.webcontainer",
    "ai.meteor.kcode.skill",
    "ai.meteor.kcode.export",
    "ai.meteor.kcode.ApplicationHostOptions",
    "ai.meteor.kcode.AgentModelRuntime",
    "ai.meteor.kcode.AgentLifecycle",
    "ai.meteor.kcode.AgentLifecycle\$None",
    "ai.meteor.kcode.AgentLifecycle\$DefaultImpls",
    "ai.meteor.kcode.ToolExecutionLifecycle",
    "ai.meteor.kcode.ToolExecutionLifecycle\$None",
    "ai.meteor.kcode.ToolExecutionLifecycle\$DefaultImpls",
    "ai.meteor.kcode.ApplicationContent",
    "ai.meteor.kcode.ApplicationContent\$DefaultImpls",
    "ai.meteor.kcode.AgentRuntimeOwner",
    "ai.meteor.kcode.KcodeAgentRuntime",
    "ai.meteor.kcode.AgentConversationOverlayController",
    "ai.meteor.kcode.AgentConversationOverlayTurn",
    "ai.meteor.kcode.AgentToolContext",
    "ai.meteor.kcode.AgentContinuationContext",
    "ai.meteor.kcode.SubagentCoordinatorFactory",
    "ai.meteor.kcode.SubagentCoordinatorFactory\$Companion",
    "ai.meteor.kcode.SubagentCoordinator",
    "ai.meteor.kcode.SubAgentLaunch",
    "ai.meteor.kcode.SubAgentSnapshot",
    "ai.meteor.kcode.ToolExecutionRequest",
    "androidx.compose",
    "androidx.activity",
    "androidx.savedstate",
    "androidx.lifecycle",
    // SQLite JNI is packaged by the native host; product Room/DAO implementations remain isolated.
    "androidx.sqlite",
    "androidx.datastore",
    "okio",
    "com.tencent.mmkv",
    "rikka.shizuku",
    "ai.meteor.kcode.shell",
    "ai.koog",
)
